# Generated by Django 5.0.1 on 2024-07-06 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pommelogy', '0002_applevariety'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageIdentify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='apple_images/')),
                ('identify_date', models.DateTimeField(auto_now_add=True)),
                ('identified_variety', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
