# Generated by Django 5.0.1 on 2024-07-06 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pommelogy', '0003_imageidentify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageidentify',
            name='user',
        ),
    ]
